
var Countries = [
[{Country: "Afghanistan" , Capital: "Kabul"}],
[{Country: "Albania", Capital: "Tirana"}],
[{Country: "Andorra", Capital: "Andorra la Vella"}],
[{Country: "Angola", Capital: "Luanda"}],
[{Country: "Antigua and Barbuda", Capital: "St Johns"}],
[{Country: "Argentina", Capital: "Buenos Aires"}],
[{Country: "Armenia", Capital: "Yerevan"}],
[{Country: "Australia", Capital: "Canberra"}],
[{Country: "Austria", Capital: "Vienna"}],
[{Country: "Azerbaijan",Capital: "Baku"}],
[{Country: "Bahamas",Capital: "Nassau"}],
[{Country: "Bahrain", Capital: "Manama"}],
[{Country: "Bangladesh", Capital: "Dhaka"}],
[{Country: "Barbados", Capital: "Bridgetown"}],
[{Country: "Belarus", Capital: "Minsk"}],
[{Country: "Belgium", Capital: "Brussels"}],
[{Country: "Belize", Capital: "Belmopan"}],
[{Country: "Benin", Capital: "Porto Novo, Cotonou"}],
[{Country: "Bhutan", Capital: ",Thimphu"}],
[{Country: "Bolivia", Capital: "La Paz and Sucre"}],
[{Country: "Bosnia and Herzegovina", Capital: "Sarajevo"}],
[{Country: "Botswana", Capital: "Gaborone"}],
[{Country: "Brazil", Capital: "Brasília"}],
[{Country: "Brunei", Capital: "Bandar Seri Begawan"}],
[{Country: "Bulgaria", Capital: "Sofia"}],
[{Country: "Burkina Faso", Capital: "Ouagadougou"}],
[{Country: "Burundi", Capital: "Bujumbura"}],
[{Country: "Cambodia", Capital: "Phnom Penh"}],
[{Country: "Cameroon", Capital: "Yaoundé"}],
[{Country: "Canada", Capital: "Ottawa"}],
[{Country: "Cape Verde", Capital: "Praia"}],
[{Country: "Cayman Islands", Capital: "George Town"}],
[{Country: "Central African Republic", Capital: "Bangui"}],
[{Country: "Chad", Capital: "N-Djamena"}],
[{Country: "Chile", Capital: "Santiago"}],
[{Country: "China", Capital: "Beijing"}],
[{Country: "Colombia", Capital: "Bogotá"}],
[{Country: "Comoros", Capital: "Moroni"}],
[{Country: "Costa Rica", Capital: "San José"}],
[{Country: "Côte d’Ivoire", Capital: "Yamoussoukro"}],
[{Country: "Croatia", Capital: "Zagreb"}],
[{Country: "Cuba", Capital: "Havana"}],
[{Country: "Cyprus", Capital: "Nicosia"}],
[{Country: "Czech Republic", Capital: "Prague"}],
[{Country: "Democratic Republic of the Congo", Capital: "Kinshasa"}],
[{Country: "Denmark", Capital: "Copenhagen"}],
[{Country: "Djibouti", Capital: "Djibouti"}],
[{Country: "Dominica", Capital: "Roseau"}],
[{Country: "Dominican Republic", Capital: "Santo Domingo"}],
[{Country: "East Timor", Capital: "Dili"}],
[{Country: "Ecuador", Capital: "Quito"}],
[{Country: "Egypt", Capital: "Cairo"}],
[{Country: "El Salvador", Capital: "San Salvador"}],
[{Country: "Equatorial Guinea", Capital: "Malabo"}],
[{Country: "Eritrea", Capital: "Asmara"}],
[{Country: "Estonia", Capital: "Tallinn"}],
[{Country: "Ethiopia", Capital: "Addis Ababa"}],
[{Country: "Fiji", Capital: "Suva"}],
[{Country: "Finland", Capital: "Helsinki"}],
[{Country: "France", Capital: "Paris"}],
[{Country: "French Guiana", Capital: "Cayenne"}],
[{Country: "Gabon", Capital: "Libreville"}],
[{Country: "Georgia", Capital: "Tbilisi"}],
[{Country: "Germany", Capital: "Berlin"}],
[{Country: "Ghana", Capital: "Accra"}],
[{Country: "Greece", Capital: "Athens"}],
[{Country: "Grenada", Capital: "St George’s"}],
[{Country: "Guatemala", Capital: "Guatemala"}],
[{Country: "Guyana", Capital: "Georgetown"}],
[{Country: "Haiti", Capital: "Port-au-Prince"}],
[{Country: "Honduras", Capital: "Tegucigalpa"}],
[{Country: "Hungary", Capital: "Budapest"}],
[{Country: "Iceland", Capital: "Reykjavik"}],
[{Country: "India", Capital: "New Delhi"}],
[{Country: "Indonesia", Capital: "Jakarta"}],
[{Country: "Iran", Capital: "Tehran"}],
[{Country: "Iraq", Capital: "Baghdad"}],
[{Country: "Israel", Capital: "Jerusalem"}],
[{Country: "Italy", Capital: "Rome"}],
[{Country: "Jamaica", Capital: "Kingston, Jamaica"}],
[{Country: "Japan", Capital: "Tokyo"}],
[{Country: "Jordan", Capital: "Amman"}],
[{Country: "Kazakhstan", Capital: "Astana"}],
[{Country: "Kenya", Capital: "Nairobi"}],
[{Country: "Kiribati", Capital: "South Tarawa"}],
[{Country: "Kuwait", Capital: "Kuwait"}],
[{Country: "Kyrgyzstan", Capital: "Bishkek"}],
[{Country: "Laos", Capital: "Vientiane"}],
[{Country: "Latvia", Capital: "Riga"}],
[{Country: "Lebanon", Capital: "Beirut"}],
[{Country: "Lesotho", Capital: "Maseru"}],
[{Country: "Liberia", Capital: "Monrovia"}],
[{Country: "Libya", Capital: "Tripoli"}],
[{Country: "Liechtenstein", Capital: "Vaduz"}],
[{Country: "Lithuania", Capital: "Vilnius"}],
[{Country: "Luxembourg", Capital: "Luxembourg City"}],
[{Country: "Madagascar", Capital: "Antananarivo"}],
[{Country: "Malawi", Capital: "Lilongwe"}],
[{Country: "Malaysia", Capital: "Kuala Lumpur"}],
[{Country: "Maldives", Capital: "Malé"}],
[{Country: "Mali", Capital: "Bamako"}],
[{Country: "Marshall Islands", Capital: "Majuro"}],
[{Country: "Mauritania", Capital: "Nouakchott"}],
[{Country: "Mauritius", Capital: "Port Louis"}],
[{Country: "Mexico", Capital: "Mexico City"}],
[{Country: "Micronesia", Capital: "Palikir"}],
[{Country: "Moldova", Capital: "Chisinau"}],
[{Country: "Monaco", Capital: "Monaco"}],
[{Country: "Mongolia", Capital: "Ulaanbaatar"}],
[{Country: "Montenegro", Capital: "Podgorica"}],
[{Country: "Morocco", Capital: "Rabat"}],
[{Country: "Mozambique", Capital: "Maputo"}],
[{Country: "Myanmar", Capital: "Naypyidaw"}],
[{Country: "Namibia", Capital: "Windhoek"}],
[{Country: "Nauru", Capital: "Yaren"}],
[{Country: "Nepal", Capital: "Kathmandu"}],
[{Country: "Netherlands ", Capital: "Amsterdam"}],
[{Country: "New Zealand", Capital: "Wellington"}],
[{Country: "Nicaragua", Capital: "Managua"}],
[{Country: "Niger", Capital: "Niamey"}],
[{Country: "Nigeria", Capital: "Abuja"}],
[{Country: "North Korea", Capital: "Pyongyang"}],
[{Country: "Norway", Capital: "Oslo"}],
[{Country: "Oman", Capital: "Muscat"}],
[{Country: "Pakistan", Capital: "Islamabad"}],
[{Country: "Palau", Capital: "Koror"}],
[{Country: "Palestine", Capital: "Jerusalem"}],
[{Country: "Panama", Capital: "Panama City"}],
[{Country: "Papua New Guinea", Capital: "Port Moresby"}],
[{Country: "Paraguay", Capital: "Asuncion"}],
[{Country: "Peru", Capital: "Lima"}],
[{Country: "Philippines", Capital: "Manila"}],
[{Country: "Poland", Capital: "Warsaw"}],
[{Country: "Portugal", Capital: "Lisbon"}],
[{Country: "Puerto Rico", Capital: "San Juan"}],
[{Country: "Qatar", Capital: "Doha"}],
[{Country: "Republic of Ireland", Capital: "Dublin"}],
[{Country: "Republic of Macedonia", Capital: "Skopje"}],
[{Country: "Republic of the Congo", Capital: "Brazzaville"}],
[{Country: "Romania", Capital: "Bucharest"}],
[{Country: "Russia", Capital: "Moscow"}],
[{Country: "Rwanda", Capital: "Kigali"}],
[{Country: "Saint Kitts and Nevis", Capital: "Basseterre"}],
[{Country: "Saint Lucia", Capital: "Castries"}],
[{Country: "Saint Vincent and the Grenadines", Capital: "Kingstown"}],
[{Country: "Samoa", Capital: "Apia"}],
[{Country: "San Marino", Capital: "San Marino"}],
[{Country: "São Tomé and Príncipe", Capital: "São Tomé"}],
[{Country: "Saudi Arabia", Capital: "Riyadh"}],
[{Country: "Senegal", Capital: "Dakar"}],
[{Country: "Serbia", Capital: "Belgrade"}],
[{Country: "Seychelles", Capital: "Victoria, Seychelles"}],
[{Country: "Sierra Leone", Capital: "Freetown"}],
[{Country: "Singapore", Capital: "Singapore"}],
[{Country: "Slovakia", Capital: "Bratislava"}],
[{Country: "Slovenia", Capital: "Ljubljana"}],
[{Country: "Solomon Islands", Capital: "Honiara"}],
[{Country: "Somalia", Capital: "Mogadishu"}],
[{Country: "South Africa", Capital: "Pretoria"}],
[{Country: "South Korea", Capital: "Seoul"}],
[{Country: "South Sudan", Capital: "Juba"}],
[{Country: "Spain", Capital: "Madrid"}],
[{Country: "Sri Lanka", Capital: "Sri Jayawardenapura Kotte"}],
[{Country: "Sudan", Capital: "Khartoum"}],
[{Country: "Suriname", Capital: "Paramaribo"}],
[{Country: "Swaziland", Capital: "Mbabane"}],
[{Country: "Sweden", Capital: "Stockholm"}],
[{Country: "Switzerland", Capital: "Bern"}],
[{Country: "Syria", Capital: "Damascus"}],
[{Country: "Taiwan", Capital: "Taipei"}],
[{Country: "Taiwan", Capital: "Taipei"}],
[{Country: "Tajikistan", Capital: "Dushanbe"}],
[{Country: "Tanzania", Capital: "Dar es Salaam, Dodoma"}],
[{Country: "Thailand", Capital: "Bangkok"}],
[{Country: "The Gambia", Capital: "Banjul"}],
[{Country: "Togo", Capital: "Lome"}],
[{Country: "Tonga", Capital: "Nuku’alofa"}],
[{Country: "Trinidad and Tobago", Capital: "Port of Spain"}],
[{Country: "Tunisia", Capital: "Tunis"}],
[{Country: "Turkey", Capital: "Ankara"}],
[{Country: "Turkey", Capital: "Ankara"}],
[{Country: "Turkmenistan", Capital: "Asgabat"}],
[{Country: "Turks and Caicos", Capital: "Cockburn Town"}],
[{Country: "Tuvalu", Capital: "Funafuti"}],
[{Country: "Uganda", Capital: "Kampala"}],
[{Country: "Ukraine", Capital: "Kyiv or Kiev"}],
[{Country: "United Arab Emirates", Capital: "Abu Dhabi"}],
[{Country: "United Kingdom", Capital: "London"}],
[{Country: "United States", Capital: "Washington DC"}],
[{Country: "Uruguay", Capital: "Montevideo"}],
[{Country: "Uzbekistan", Capital: "Tashkent"}],
[{Country: "Vanuatu", Capital: "Port Vila"}],
[{Country: "Vatican City", Capital: "Vatican City"}],
[{Country: "Venezuela", Capital: "Caracas"}],
[{Country: "Vietnam", Capital: "Hanoi"}],
[{Country: "Western Sahara", Capital: "La’youn"}],
[{Country: "Yemen", Capital: "Sana’a"}],
[{Country: "Zambia", Capital: "Lusaka"}],
[{Country: "Zimbabwe", Capital: "Harare"}]
];
